server:
  port: 8080
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.1:8848 # 配置Nacos地址
        namespace: f059b933-a68c-4633-afb0-c28d7478fb30 # prod空间
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace} # dev命名空间
        file-extension: yaml
    sentinel:
      transport:
        dashboard: 172.17.0.1:8858 # 配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，假设被占用，会从8719依次+1扫描，直至找到未被占用的端口
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: consumer_get_payment
          #          uri: http://localhost:7001          #匹配后提供服务的路由地址
          uri: lb://cloud-consumer-service # 匹配后提供服务的动态路由地址
          predicates:
            - Path=/payment/**

        - id: consumer_payment # payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-consumer-service         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment        # 断言，路径相匹配的进行路由
            - After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
        #            - Cookie=username,zzyy
        #            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

        - id: flask_demo
          uri: lb://cloud-flask-service
          predicates:
            - Path=/flask/**
