server:
  port: 7001

spring:
  application:
    name: cloud-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置Nacos地址

service-url:
  nacos-provider-service: http://cloud-provider-service
