server:
  port: 7001
spring:
  application:
    name: cloud-consumer-devservice
  cloud:
    sentinel:
      transport:
        dashboard: 49.234.60.188:8858
        port: 8719

service-url:
  nacos-provider-service: http://cloud-provider-devservice

# 激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
