server:
  port: 8080
spring:
  application:
    name: cloud-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.1:8848 # 配置Nacos地址
        namespace: f059b933-a68c-4633-afb0-c28d7478fb30 # prod空间
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace} # dev命名空间
        file-extension: yaml
    sentinel:
      transport:
        dashboard: 172.17.0.1:8858 # 配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，假设被占用，会从8719依次+1扫描，直至找到未被占用的端口

service-url:
  nacos-provider-service: http://cloud-provider-service

# 激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true