server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://172.17.0.1:3306/group2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
