server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/dbplay?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置Nacos地址
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858 # 配置Sentinel dashboard地址
      datasource:
        ds1: # 把sentinel规则持久化到nacos
          nacos:
            server-addr: localhost:8848 # nacos地址
