server:
  port: 8001
config:
  info: from local file application-dev
spring:
  application:
    name: cloud-provider-devservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/dbplay?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    sentinel:
      transport:
        dashboard: 49.234.60.188:8858 # 配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，假设被占用，会从8719依次+1扫描，直至找到未被占用的端口
      datasource:
        ds1: # 把sentinel规则持久化到nacos
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#  redis:
#    url: redis://offline:Ypx123456@r-bp1syyjqposds431iipd.redis.rds.aliyuncs.com:6379
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.group2.entities    # 所有Entity别名类所在包，xml就方便找

management:
  endpoints:
    web:
      exposure:
        include: '*'