server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://172.17.0.1:3306/group2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.1:8848 # 配置Nacos地址
      config:
        server-addr: 172.17.0.1:8848
    sentinel:
      transport:
        dashboard: 172.17.0.1:8858 # 配置Sentinel dashboard地址
      datasource:
        ds1: # 把sentinel规则持久化到nacos
          nacos:
            server-addr: 172.17.0.1:8848 # nacos地址
